services:
  - type: web
    name: springboot-mongo-app
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/Despliegue_Lab10-0.0.1-SNAPSHOT.jar
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: my-mongodb
          property: connectionString
