services:
  - type: web
    name: springboot-mongo-app
    env: java
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MONGODB_URI
        value: mongodb+srv://ariadnanolasco:CFtOC5N7Pu8k1b1r@cluster0.jrsgowe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar